-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. TABLES
CREATE TABLE public.customers (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    code TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    tax_id TEXT,
    branch TEXT DEFAULT '',
    credit_term INTEGER DEFAULT 0,
    contact_person TEXT,
    email TEXT,
    phone TEXT,
    fax TEXT,
    address TEXT,
    status TEXT DEFAULT 'Active'
);

CREATE TABLE public.purchase_orders (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    po_number TEXT UNIQUE NOT NULL,
    customer_id BIGINT REFERENCES public.customers(id) ON DELETE SET NULL,
    issue_date DATE NOT NULL DEFAULT CURRENT_DATE,
    due_date DATE,
    status TEXT DEFAULT 'Pending',
    file_url TEXT,
    notes TEXT,
    vat_rate NUMERIC(15, 2) DEFAULT 7.0,
    vat_amount NUMERIC(15, 2) DEFAULT 0,
    total_amount NUMERIC(15, 2) DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.purchase_order_items (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    po_id UUID REFERENCES public.purchase_orders(id) ON DELETE CASCADE,
    product_name TEXT NOT NULL,
    quantity NUMERIC(15, 3) DEFAULT 1,
    unit TEXT,
    price_per_unit NUMERIC(15, 2) DEFAULT 0,
    amount NUMERIC(15, 2) DEFAULT 0,
    sort_order INTEGER DEFAULT 0
);

CREATE TABLE public.invoices (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    invoice_no TEXT UNIQUE NOT NULL,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    customer_id BIGINT REFERENCES public.customers(id) ON DELETE SET NULL,
    purchase_order_id UUID REFERENCES public.purchase_orders(id) ON DELETE SET NULL,
    customer_snapshot JSONB,
    reference_no TEXT,
    credit_days INTEGER DEFAULT 0,
    due_date DATE,
    subtotal NUMERIC(15, 2) DEFAULT 0,
    discount NUMERIC(15, 2) DEFAULT 0,
    vat_rate NUMERIC(15, 2) DEFAULT 7.0,
    vat_amount NUMERIC(15, 2) DEFAULT 0,
    grand_total NUMERIC(15, 2) DEFAULT 0,
    baht_text TEXT,
    notes TEXT,
    adjustments JSONB DEFAULT '[]'::jsonb,
    status TEXT DEFAULT 'Draft',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.invoice_items (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    invoice_id UUID REFERENCES public.invoices(id) ON DELETE CASCADE,
    product_name TEXT NOT NULL,
    quantity NUMERIC(15, 3) DEFAULT 1,
    unit TEXT,
    price_per_unit NUMERIC(15, 2) DEFAULT 0,
    amount NUMERIC(15, 2) DEFAULT 0,
    sort_order INTEGER DEFAULT 0
);

CREATE TABLE public.billing_notes (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    billing_note_no TEXT UNIQUE NOT NULL,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    customer_id BIGINT REFERENCES public.customers(id) ON DELETE SET NULL,
    customer_snapshot JSONB,
    total_amount NUMERIC(15, 2) DEFAULT 0,
    status TEXT DEFAULT 'Draft',
    notes TEXT,
    baht_text TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.billing_note_items (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    billing_note_id UUID REFERENCES public.billing_notes(id) ON DELETE CASCADE,
    invoice_id UUID REFERENCES public.invoices(id) ON DELETE CASCADE,
    sort_order INTEGER DEFAULT 0,
    UNIQUE(billing_note_id, invoice_id)
);

CREATE TABLE public.employees (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    code TEXT UNIQUE NOT NULL,
    full_name TEXT NOT NULL,
    date_of_birth DATE,
    address TEXT,
    phone TEXT,
    position TEXT,
    employment_type TEXT DEFAULT 'Full-time',
    daily_wage NUMERIC(10, 2) DEFAULT 0,
    diligence_allowance NUMERIC DEFAULT 0,
    start_date DATE DEFAULT CURRENT_DATE,
    status TEXT DEFAULT 'Active',
    emergency_contact_name TEXT,
    emergency_contact_phone TEXT,
    emergency_contact_relation TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.work_logs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    employee_id UUID REFERENCES public.employees(id) ON DELETE CASCADE,
    work_date DATE NOT NULL DEFAULT CURRENT_DATE,
    work_days NUMERIC(3, 1) DEFAULT 1.0,
    ot_hours NUMERIC(4, 1) DEFAULT 0.0,
    note TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.staff_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    email TEXT,
    username TEXT UNIQUE,
    password TEXT,
    permissions JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.settings (
    key TEXT PRIMARY KEY,
    value JSONB NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.company_info (
    id BIGINT PRIMARY KEY DEFAULT 1,
    name TEXT,
    address TEXT,
    phone TEXT,
    fax TEXT,
    email TEXT,
    tax_id TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT single_row CHECK (id = 1)
);

-- 3. RLS
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchase_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchase_order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoice_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.billing_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.billing_note_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.work_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.staff_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.company_info ENABLE ROW LEVEL SECURITY;

-- 4. POLICIES (Allow All for simplified test setup)
CREATE POLICY "Allow All" ON public.customers FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow All" ON public.purchase_orders FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow All" ON public.purchase_order_items FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow All" ON public.invoices FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow All" ON public.invoice_items FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow All" ON public.billing_notes FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow All" ON public.billing_note_items FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow All" ON public.employees FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow All" ON public.work_logs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow All" ON public.staff_members FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow All" ON public.settings FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow All" ON public.company_info FOR ALL USING (true) WITH CHECK (true);

-- 5. INITIAL DATA
INSERT INTO public.company_info (id, name) VALUES (1, 'My Factory Store (Test)') ON CONFLICT DO NOTHING;
INSERT INTO public.settings (key, value) VALUES ('work_schedule', '{"start_time": "08:00", "end_time": "17:00"}') ON CONFLICT DO NOTHING;
