-- MASTER SCHEMA SETUP (One-stop-shop for a fresh database)
-- This file includes Customers, Invoices, Invoice Items, Customer Products, Billing Notes, and Staff

-- 1. Enable Extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. CREATE CUSTOMERS TABLE
CREATE TABLE IF NOT EXISTS public.customers (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    code TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    tax_id TEXT,
    branch TEXT DEFAULT 'สำนักงานใหญ่',
    credit_term INTEGER DEFAULT 0,
    contact_person TEXT,
    email TEXT,
    phone TEXT,
    fax TEXT,
    address TEXT,
    status TEXT DEFAULT 'Active'
);

-- 3. CREATE INVOICES TABLE (Includes Customer Snapshot)
CREATE TABLE IF NOT EXISTS public.invoices (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    invoice_no TEXT UNIQUE NOT NULL,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    customer_id BIGINT REFERENCES public.customers(id) ON DELETE SET NULL,
    customer_snapshot JSONB, -- Stores flat customer data for historical accuracy
    reference_no TEXT,
    credit_days INTEGER DEFAULT 0,
    due_date DATE,
    subtotal NUMERIC(15, 2) DEFAULT 0,
    discount NUMERIC(15, 2) DEFAULT 0,
    vat_rate NUMERIC(15, 2) DEFAULT 7.0,
    vat_amount NUMERIC(15, 2) DEFAULT 0,
    grand_total NUMERIC(15, 2) DEFAULT 0,
    baht_text TEXT,
    notes TEXT,
    adjustments JSONB DEFAULT '[]'::jsonb,
    status TEXT DEFAULT 'Draft',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. CREATE INVOICE ITEMS TABLE
CREATE TABLE IF NOT EXISTS public.invoice_items (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    invoice_id UUID REFERENCES public.invoices(id) ON DELETE CASCADE,
    product_name TEXT NOT NULL,
    quantity NUMERIC(15, 3) DEFAULT 1,
    unit TEXT,
    price_per_unit NUMERIC(15, 2) DEFAULT 0,
    amount NUMERIC(15, 2) DEFAULT 0,
    sort_order INTEGER DEFAULT 0
);

-- 5. CREATE CUSTOMER PRODUCTS TABLE
CREATE TABLE IF NOT EXISTS public.customer_products (
    id BIGSERIAL PRIMARY KEY,
    customer_id BIGINT REFERENCES public.customers(id) ON DELETE CASCADE NOT NULL,
    name TEXT NOT NULL,
    unit TEXT,
    price NUMERIC(15, 2) DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. CREATE CUSTOMER ATTRIBUTES TABLE
CREATE TABLE IF NOT EXISTS public.customer_attributes (
    id BIGSERIAL PRIMARY KEY,
    customer_id BIGINT REFERENCES public.customers(id) ON DELETE CASCADE NOT NULL,
    attribute_name TEXT NOT NULL,
    attribute_value TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. CREATE BILLING NOTES TABLE (Includes Customer Snapshot)
CREATE TABLE IF NOT EXISTS public.billing_notes (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    billing_note_no TEXT UNIQUE NOT NULL,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    customer_id BIGINT REFERENCES public.customers(id) ON DELETE SET NULL,
    customer_snapshot JSONB,
    total_amount NUMERIC(15, 2) DEFAULT 0,
    status TEXT DEFAULT 'Draft',
    notes TEXT,
    baht_text TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. CREATE BILLING NOTE ITEMS TABLE
CREATE TABLE IF NOT EXISTS public.billing_note_items (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    billing_note_id UUID REFERENCES public.billing_notes(id) ON DELETE CASCADE,
    invoice_id UUID REFERENCES public.invoices(id) ON DELETE CASCADE,
    sort_order INTEGER DEFAULT 0,
    UNIQUE(billing_note_id, invoice_id)
);

-- 8. CREATE STAFF MEMBERS TABLE (With Permissions)
CREATE TABLE IF NOT EXISTS public.staff_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    email TEXT,
    username TEXT UNIQUE,
    password TEXT,
    permissions JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Default Admin User (Password: admin123)
INSERT INTO public.staff_members (full_name, username, password, permissions)
VALUES ('Admin', 'admin', '$2b$10$gozKeogcPH4Rht7ocnGHl.ssh5.3.c6KI4HKJgXhdC8RscyOKBvN2', '{
  "customers": {"view": true, "create": true, "edit": true, "delete": true},
  "company_info": {"view": true, "edit": true},
  "users": {"view": true, "create": true, "edit": true, "delete": true},
  "production": {"view": true, "create": true, "edit": true, "delete": true},
  "invoices": {"view": true, "create": true, "edit": true, "delete": true},
  "billing_notes": {"view": true, "create": true, "edit": true, "delete": true}
}'::jsonb)
ON CONFLICT (username) DO NOTHING;

-- 10. CREATE COMPANY INFO TABLE (Single Row)
CREATE TABLE IF NOT EXISTS public.company_info (
    id BIGINT PRIMARY KEY DEFAULT 1,
    name TEXT,
    address TEXT,
    phone TEXT,
    fax TEXT,
    email TEXT,
    tax_id TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT single_row CHECK (id = 1)
);

-- Default Company Info
INSERT INTO public.company_info (id, name, updated_at)
VALUES (1, 'My Factory', NOW())
ON CONFLICT (id) DO NOTHING;

-- 11. ENABLE RLS
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoice_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customer_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.billing_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.billing_note_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.billing_note_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.staff_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customer_attributes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.company_info ENABLE ROW LEVEL SECURITY;

-- 11. CREATE POLICIES (Development: Allow All)
-- 12. CREATE POLICIES (Security: Authenticated Users Only)
DO $$
BEGIN
    -- Customers
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'customers' AND policyname = 'Enable access to authenticated users only') THEN
        CREATE POLICY "Enable access to authenticated users only" ON public.customers FOR ALL TO authenticated USING (true) WITH CHECK (true);
    END IF;
    -- Invoices
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'invoices' AND policyname = 'Enable access to authenticated users only') THEN
        CREATE POLICY "Enable access to authenticated users only" ON public.invoices FOR ALL TO authenticated USING (true) WITH CHECK (true);
    END IF;
    -- Invoice Items
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'invoice_items' AND policyname = 'Enable access to authenticated users only') THEN
        CREATE POLICY "Enable access to authenticated users only" ON public.invoice_items FOR ALL TO authenticated USING (true) WITH CHECK (true);
    END IF;
    -- Customer Products
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'customer_products' AND policyname = 'Enable access to authenticated users only') THEN
        CREATE POLICY "Enable access to authenticated users only" ON public.customer_products FOR ALL TO authenticated USING (true) WITH CHECK (true);
    END IF;
    -- Billing Notes
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'billing_notes' AND policyname = 'Enable access to authenticated users only') THEN
        CREATE POLICY "Enable access to authenticated users only" ON public.billing_notes FOR ALL TO authenticated USING (true) WITH CHECK (true);
    END IF;
    -- Billing Note Items
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'billing_note_items' AND policyname = 'Enable access to authenticated users only') THEN
        CREATE POLICY "Enable access to authenticated users only" ON public.billing_note_items FOR ALL TO authenticated USING (true) WITH CHECK (true);
    END IF;
    -- Staff Members
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'staff_members' AND policyname = 'Enable access to authenticated users only') THEN
        CREATE POLICY "Enable access to authenticated users only" ON public.staff_members FOR ALL TO authenticated USING (true) WITH CHECK (true);
    END IF;
    -- Customer Attributes
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'customer_attributes' AND policyname = 'Enable access to authenticated users only') THEN
        CREATE POLICY "Enable access to authenticated users only" ON public.customer_attributes FOR ALL TO authenticated USING (true) WITH CHECK (true);
    END IF;
    -- Company Info
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'company_info' AND policyname = 'Enable access to authenticated users only') THEN
        CREATE POLICY "Enable access to authenticated users only" ON public.company_info FOR ALL TO authenticated USING (true) WITH CHECK (true);
    END IF;
END $$;

-- 11. REFRESH SCHEMA CACHE
NOTIFY pgrst, 'reload schema';
