ALTER TABLE public.payroll_periods 
ADD COLUMN IF NOT EXISTS name TEXT,
ADD COLUMN IF NOT EXISTS start_date DATE,
ADD COLUMN IF NOT EXISTS end_date DATE,
ADD COLUMN IF NOT EXISTS working_days INTEGER,
ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'draft',
ADD COLUMN IF NOT EXISTS created_by TEXT;

-- We also created payroll_entries, let's make sure its columns exist
ALTER TABLE public.payroll_entries
ADD COLUMN IF NOT EXISTS actual_working_days NUMERIC,
ADD COLUMN IF NOT EXISTS position_allowance NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS skill_allowance NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS daily_wage NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS ot_hours NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS ot_1_5_hours NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS ot_2_0_hours NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS ot_3_0_hours NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS transport_allowance NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS bonus NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS backpay NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS shift_allowance NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS company_loan_deduction NUMERIC DEFAULT 0;

NOTIFY pgrst, 'reload schema';
